name: Publish package

on:
  workflow_run:
    workflows: ["Create release"]
    types: [completed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout source code"
      uses: "actions/checkout@v3"
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}